services:
  db-courrier-service:
    image: mysql:8.0
    container_name: db-courrier
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-formation
      MYSQL_USER: devops
      MYSQL_PASSWORD: devopspass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_backup:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-courrier-service:
    build: .
    container_name: backend-courrier
    restart: always
    ports:
      - "8900:8900"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-courrier-service:3306/db-formation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: devopspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db-courrier-service:
        condition: service_healthy

  phpmyadmin-courrier-service:
    image: phpmyadmin
    container_name: phpmyadmin-courrier
    restart: always
    depends_on:
      - db-courrier-service                  # correspond au nom du service bd
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db-courrier-service          # correspond au nom du service bd

volumes:
  mysql_data_backup: